# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cv_service_pb2 as cv__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cv_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectServiceStub(object):
    """检测服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/cv_service.DetectService/Detect',
                request_serializer=cv__service__pb2.DetectRequest.SerializeToString,
                response_deserializer=cv__service__pb2.DetectResponse.FromString,
                _registered_method=True)


class DetectServiceServicer(object):
    """检测服务定义
    """

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=cv__service__pb2.DetectRequest.FromString,
                    response_serializer=cv__service__pb2.DetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cv_service.DetectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cv_service.DetectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectService(object):
    """检测服务定义
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cv_service.DetectService/Detect',
            cv__service__pb2.DetectRequest.SerializeToString,
            cv__service__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrackAlertServiceStub(object):
    """跟踪告警服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackAndAlert = channel.unary_unary(
                '/cv_service.TrackAlertService/TrackAndAlert',
                request_serializer=cv__service__pb2.TrackAlertRequest.SerializeToString,
                response_deserializer=cv__service__pb2.TrackAlertResponse.FromString,
                _registered_method=True)


class TrackAlertServiceServicer(object):
    """跟踪告警服务定义
    """

    def TrackAndAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackAlertServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackAndAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackAndAlert,
                    request_deserializer=cv__service__pb2.TrackAlertRequest.FromString,
                    response_serializer=cv__service__pb2.TrackAlertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cv_service.TrackAlertService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cv_service.TrackAlertService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackAlertService(object):
    """跟踪告警服务定义
    """

    @staticmethod
    def TrackAndAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cv_service.TrackAlertService/TrackAndAlert',
            cv__service__pb2.TrackAlertRequest.SerializeToString,
            cv__service__pb2.TrackAlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
