# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cv_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cv_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63v_service.proto\x12\ncv_service\"F\n\x05\x46rame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\"a\n\tDetection\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\"\x1d\n\rForbiddenArea\x12\x0c\n\x04rect\x18\x01 \x03(\x05\"F\n\tAlertRule\x12(\n\x05\x61reas\x18\x01 \x03(\x0b\x32\x19.cv_service.ForbiddenArea\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\"c\n\x0b\x41lertResult\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\n\n\x02x1\x18\x02 \x01(\x05\x12\n\n\x02y1\x18\x03 \x01(\x05\x12\n\n\x02x2\x18\x04 \x01(\x05\x12\n\n\x02y2\x18\x05 \x01(\x05\x12\x12\n\nalert_type\x18\x06 \x01(\x05\"E\n\rDetectRequest\x12 \n\x05\x66rame\x18\x01 \x01(\x0b\x32\x11.cv_service.Frame\x12\x12\n\nconf_thres\x18\x02 \x01(\x02\"\x7f\n\x0e\x44\x65tectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12)\n\ndetections\x18\x02 \x03(\x0b\x32\x15.cv_service.Detection\x12 \n\x05\x66rame\x18\x03 \x01(\x0b\x32\x11.cv_service.Frame\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x8b\x01\n\x11TrackAlertRequest\x12 \n\x05\x66rame\x18\x01 \x01(\x0b\x32\x11.cv_service.Frame\x12)\n\ndetections\x18\x02 \x03(\x0b\x32\x15.cv_service.Detection\x12)\n\nalert_rule\x18\x03 \x01(\x0b\x32\x15.cv_service.AlertRule\"\x81\x01\n\x12TrackAlertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12 \n\x05\x66rame\x18\x02 \x01(\x0b\x32\x11.cv_service.Frame\x12\'\n\x06\x61lerts\x18\x03 \x03(\x0b\x32\x17.cv_service.AlertResult\x12\x0f\n\x07message\x18\x04 \x01(\t2P\n\rDetectService\x12?\n\x06\x44\x65tect\x12\x19.cv_service.DetectRequest\x1a\x1a.cv_service.DetectResponse2c\n\x11TrackAlertService\x12N\n\rTrackAndAlert\x12\x1d.cv_service.TrackAlertRequest\x1a\x1e.cv_service.TrackAlertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cv_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=32
  _globals['_FRAME']._serialized_end=102
  _globals['_DETECTION']._serialized_start=104
  _globals['_DETECTION']._serialized_end=201
  _globals['_FORBIDDENAREA']._serialized_start=203
  _globals['_FORBIDDENAREA']._serialized_end=232
  _globals['_ALERTRULE']._serialized_start=234
  _globals['_ALERTRULE']._serialized_end=304
  _globals['_ALERTRESULT']._serialized_start=306
  _globals['_ALERTRESULT']._serialized_end=405
  _globals['_DETECTREQUEST']._serialized_start=407
  _globals['_DETECTREQUEST']._serialized_end=476
  _globals['_DETECTRESPONSE']._serialized_start=478
  _globals['_DETECTRESPONSE']._serialized_end=605
  _globals['_TRACKALERTREQUEST']._serialized_start=608
  _globals['_TRACKALERTREQUEST']._serialized_end=747
  _globals['_TRACKALERTRESPONSE']._serialized_start=750
  _globals['_TRACKALERTRESPONSE']._serialized_end=879
  _globals['_DETECTSERVICE']._serialized_start=881
  _globals['_DETECTSERVICE']._serialized_end=961
  _globals['_TRACKALERTSERVICE']._serialized_start=963
  _globals['_TRACKALERTSERVICE']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
